/**
 * @author mingyu
 */
export const useFeedListDummy = [
  // 0
  {
    vote: {
      id: 12,
      title: "탕수육은 어떻게 먹어야 하는가",
      image_url: "",
      content: "대충 내용",
      is_event: false,
      is_anonymous: false,
      is_public: false,
      is_closed: false,
      is_deleted: false,
      start_date: "2023-03-13 15:38:27",
      end_date: "2023-03-30 15:38:27",
      hits: 8272362,
      voted_number: 6121,
      opinion_number: 35,
      tags: ["ㅋㅋ", "이거슨 태그!"],
    },
    writer: {
      id: 1414,
      nickname: "봉천동 이연복",
      badge_image_url: "",
    },
    vote_items: [
      {
        id: 12341,
        item_number: 1,
        title: "당근 부먹 아님?? 부먹은 오래 전부터 유행했던 방식이다.",
        iframe_link: "",
        image_url: "",
        total_points: 3434165,
        voted_number: 726,
      },
      {
        id: 1234621,
        item_number: 2,
        title: "찍먹이지",
        iframe_link: "",
        image_url: "",
        total_points: 3613,
        voted_number: 76,
      },
    ],
    best_opinion: {
      id: 143,
      writer: {
        id: 12166,
        nickname: "봉천동 이연복",
        badge_image_url: "",
      },
      content: "맛있는 탕수육이란 부어도 맛있는 탕수육 아닐까?",
      agreed_number: 12512,
      disagreed_number: 133,
      created_date: "2021-03-27 18:37:27",
    },
  },
  // 1
  {
    vote: {
      id: 17261,
      title: "탕슉 먹는법",
      image_url: "",
      content: "대충 내용",
      is_event: false,
      is_anonymous: false,
      is_public: false,
      is_closed: false,
      is_deleted: false,
      start_date: "2023-03-16 15:38:27",
      end_date: "2023-04-16 15:38:27",
      hits: 11616,
      voted_number: 51,
      opinion_number: 8,
      tags: ["ㅋㅋ", "이거슨 태그!"],
    },
    writer: {
      id: 1414,
      nickname: "덕명동 슈퍼라이더",
      badge_image_url: "",
    },
    vote_items: [
      {
        id: 12341,
        item_number: 1,
        title:
          "뿌먹 뿌먹 뿌먹뿌먹 뿌먹뿌먹 뿌먹 뿌먹 뿌먹 뿌먹뿌먹뿌먹뿌먹뿌먹",
        iframe_link: "",
        image_url: "",
        total_points: 3434165,
        voted_number: 726,
      },
      {
        id: 1234621,
        item_number: 2,
        title: "찍먹이지",
        iframe_link: "",
        image_url: "",
        total_points: 3613,
        voted_number: 76,
      },
      {
        id: 1234621,
        item_number: 3,
        title: "쳐먹",
        iframe_link: "",
        image_url: "",
        total_points: 3613,
        voted_number: 76,
      },
    ],
    best_opinion: {
      id: 143,
      writer: {
        id: 12166,
        nickname: "중국인",
        badge_image_url: "",
      },
      content: "그냥 먹자",
      agreed_number: 12512,
      disagreed_number: 133,
      created_date: "2021-03-27 18:37:27",
    },
  },
  // 2
  {
    vote: {
      id: 12,
      title: "피자 브랜드의 최강자는?",
      image_url: "",
      content: "대충 내용",
      is_event: false,
      is_anonymous: false,
      is_public: false,
      is_closed: false,
      is_deleted: false,
      start_date: "2023-03-13 15:38:27",
      end_date: "2023-12-18 15:38:27",
      hits: 1854,
      voted_number: 611,
      opinion_number: 85,
      tags: ["ㅋㅋ", "이거슨 태그!"],
    },
    writer: {
      id: 1414,
      nickname: "정용진",
      badge_image_url: "",
    },
    vote_items: [
      {
        id: 12341,
        item_number: 1,
        title: "피자헛",
        iframe_link: "",
        image_url:
          "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMzAyMDlfNzYg%2FMDAxNjc1OTMxNjcwNzM3.7K5S3PN4CwRdPAFElxJLbaQGr9QSYF_V_BSL6NhHygYg.2ZtyFwcIIykNfavDunwCMCSyTfdzs6qIozIEZqvUihsg.JPEG.kimccoli%2Fphoto_2023-01-20_15-06-54.jpg&type=sc960_832",
        total_points: 3434165,
        voted_number: 726,
      },
      {
        id: 1234621,
        item_number: 2,
        title: "미스터피자",
        iframe_link: "",
        image_url:
          "https://search.pstatic.net/common/?src=http%3A%2F%2Fimgnews.naver.net%2Fimage%2F5353%2F2017%2F06%2F26%2F0000217525_001_20170626143130828.jpg&type=sc960_832",
        total_points: 3613,
        voted_number: 76,
      },
      {
        id: 1234621,
        item_number: 3,
        title: "노브랜드피자",
        iframe_link: "",
        image_url:
          "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjAzMjVfMjEw%2FMDAxNjQ4MjAwNDAyNjYz.VM9O30-cplokbJvG_X4FHV6lqQOyewbTkyIXGpPM94wg.PiHmo6UEIRlhvfzJctvUBSnChiOMNczFel6UUhgxwiwg.JPEG.leejk617%2FIMG_8552.jpeg&type=sc960_832",
        total_points: 3613,
        voted_number: 76,
      },
      {
        id: 1234621,
        item_number: 4,
        title: "피자 알볼로",
        iframe_link: "",
        image_url:
          "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA1MzBfMjU5%2FMDAxNjIyMzc0Mzk1MTgy.yXB8XnCG8Hz8GIUBJF-HAK0rH_atsZqVP2Ax71cSbKog.qsg3YsJCcdtcASnDj3EmmL4j6IzMikk8BnQ1ZDsiUXsg.JPEG.remon103%2F20210530%25A3%25DF194639.jpg&type=sc960_832",
        total_points: 3613,
        voted_number: 76,
      },
      {
        id: 1234621,
        item_number: 5,
        title: "7번가 피자",
        iframe_link: "",
        image_url:
          "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMTA4MjdfMSAg%2FMDAxNjMwMDI5NzI3Nzgx.xclZ2LQgPPKt_snvRZr0ICF5HBWU5h9KTvR8kcC9DVQg.wOl9PoMtsftEb1VEcx-P1HBOX7CpxZi_3J7adZRg16Mg.JPEG.01192076575%2FDSC00064.JPG&type=sc960_832",
        total_points: 3613,
        voted_number: 76,
      },
      {
        id: 1234621,
        item_number: 6,
        title: "어깨피자 가슴피자",
        iframe_link: "",
        image_url:
          "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMDEyMzFfMjAz%2FMDAxNjA5NDI0MDg5MTUw.2xSP8S-e01okURFbfvEpbfTvnXeuAbw_2i7BohwIjBMg.bE8AZu9AMheNqRmUAH3y3BKD7ZoMmI-IzJL6ScPMobIg.JPEG.minheuicho%2F1609424085223.jpg&type=sc960_832",
        total_points: 3613,
        voted_number: 76,
      },
    ],
    best_opinion: {
      id: 164362143,
      writer: {
        id: 166166,
        nickname: "고든 램지",
        badge_image_url:
          "https://search.pstatic.net/common/?src=http%3A%2F%2Fblogfiles.naver.net%2FMjAyMjAxMDNfMjYw%2FMDAxNjQxMjIwODczMzkx.ktC2n8XwuYOhcKCcjjJKaNYswJ0nuF8KPXRXr5-d3mQg.qebX0js7FqodyXZ1S2uZ5mrP1pNBOu4cPWbw8uKXGFUg.PNG.ebichu1030%2F20220103234058.png&type=sc960_832",
      },
      content: "고든램지 피자 어디감",
      agreed_number: 12512,
      disagreed_number: 133,
      created_date: "2021-03-27 18:37:27",
    },
  },
  {
    vote: {
      id: 1,
      title: "내가 좋아하는 색깔은 무엇인가?",
      image_url: "",
      content: "색깔에 대한 나의 선호도에 대해 투표해주세요!",
      is_event: false,
      is_anonymous: true,
      is_public: true,
      is_closed: true,
      is_deleted: false,
      start_date: "2023-04-01 08:00:00",
      end_date: "2023-04-03 23:59:59",
      hits: 62624724727,
      voted_number: 72626,
      opinion_number: 5,
      tags: ["색깔", "선호도"],
    },
    writer: {
      id: 100,
      nickname: "happy_turtle",
      badge_image_url: "",
    },
    vote_items: [
      {
        id: 1,
        item_number: 1,
        title: "빨간색",
        iframe_link: "https://dummyimage.com/250x250/ff0000/ffffff",
        image_url: "",
        total_points: 10,
        voted_number: 5,
      },
      {
        id: 2,
        item_number: 2,
        title: "파란색",
        iframe_link: "",
        image_url: "",
        total_points: 8,
        voted_number: 4,
      },
      {
        id: 3,
        item_number: 3,
        title: "초록색",
        iframe_link: "",
        image_url: "https://dummyimage.com/250x250/ff0000/ffffff",
        total_points: 6,
        voted_number: 3,
      },
      {
        id: 4,
        item_number: 4,
        title: "노란색",
        iframe_link: "",
        image_url: "",
        total_points: 4,
        voted_number: 2,
      },
    ],
    best_opinion: {
      id: 1,
      writer: {
        id: 101,
        nickname: "crazy_rabbit",
        badge_image_url: "",
      },
      content: "나는 핑크색을 좋아해요!",
      agreed_number: 10,
      disagreed_number: 2,
      created_date: "2023-04-03 10:30:00",
    },
  },
  {
    vote: {
      id: 53,
      title: "내가 생각하는 최고의 여행지는?",
      image_url: "https://picsum.photos/800/400",
      content:
        "이번 여름에 가보고 싶은 여행지를 찾고 있습니다. 여러분들이 가봤던 여행지 중에서 최고라고 생각하는 곳은 어디인가요?",
      is_event: false,
      is_anonymous: false,
      is_public: true,
      is_closed: false,
      is_deleted: false,
      start_date: "2023-03-15 10:00:00",
      end_date: "2023-04-10 23:59:59",
      hits: 2847,
      voted_number: 1896,
      opinion_number: 7,
      tags: ["여행", "최고의 여행지"],
    },
    writer: {
      id: 334,
      nickname: "wanderlust",
      badge_image_url: "https://dummyimage.com/100x100/000/fff&text=W",
    },
    vote_items: [
      {
        id: 531,
        item_number: 1,
        title: "바다가 보이는 섬",
        iframe_link: "",
        image_url: "https://dummyimage.com/640x480/000/fff&text=Island",
        total_points: 758,
        voted_number: 93,
      },
      {
        id: 532,
        item_number: 2,
        title: "산과 호수가 있는 자연",
        iframe_link: "",
        image_url: "https://dummyimage.com/640x480/000/fff&text=Mountain+Lake",
        total_points: 652,
        voted_number: 76,
      },
      {
        id: 533,
        item_number: 3,
        title: "도시의 문화와 먹거리",
        iframe_link: "",
        image_url: "https://dummyimage.com/640x480/000/fff&text=City+Cuisine",
        total_points: 521,
        voted_number: 63,
      },
      {
        id: 534,
        item_number: 4,
        title: "역사적 유산과 건축물",
        iframe_link: "",
        image_url:
          "https://dummyimage.com/640x480/000/fff&text=Historic+Architecture",
        total_points: 467,
        voted_number: 56,
      },
      {
        id: 535,
        item_number: 5,
        title: "자연과 문화를 함께 느낄 수 있는 관광지",
        iframe_link: "",
        image_url: "https://dummyimage.com/640x480/000/fff&text=Nature+Culture",
        total_points: 343,
        voted_number: 42,
      },
    ],
    best_opinion: {
      id: 5351,
      writer: {
        id: 721,
        nickname: "traveler",
        badge_image_url: "https://dummyimage.com/100x100/000/fff&text=T",
      },
      content: "안동이 최고지",
      agreed_number: 10,
      disagreed_number: 2,
      created_date: "2023-04-03 10:30:00",
    },
  },
  {
    vote: {
      id: 789,
      title: "한식 중에 가장 맛있는 음식은?",
      image_url: "https://dummyimage.com/600x400/000/fff",
      content: "한식 중에 가장 맛있는 음식은 무엇일까요?",
      is_event: false,
      is_anonymous: false,
      is_public: true,
      is_closed: false,
      is_deleted: false,
      start_date: "2023-04-01 09:00:00",
      end_date: "2023-04-15 17:00:00",
      hits: 88993,
      voted_number: 12765,
      opinion_number: 87,
      tags: ["한식", "맛집", "음식"],
    },
    writer: {
      id: 2468,
      nickname: "홍대핫도그",
      badge_image_url: "",
    },
    vote_items: [
      {
        id: 56789,
        item_number: 1,
        title: "삼계탕",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300/000/fff",
        total_points: 987,
        voted_number: 45,
      },
      {
        id: 56790,
        item_number: 2,
        title: "갈비탕",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300/000/fff",
        total_points: 654,
        voted_number: 36,
      },
      {
        id: 56791,
        item_number: 3,
        title: "떡갈비",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300/000/fff",
        total_points: 321,
        voted_number: 23,
      },
      {
        id: 56792,
        item_number: 4,
        title: "순대국밥",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300/000/fff",
        total_points: 789,
        voted_number: 54,
      },
      {
        id: 56793,
        item_number: 5,
        title: "칼국수",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300/000/fff",
        total_points: 432,
        voted_number: 31,
      },
    ],
    best_opinion: {
      id: 7890,
      writer: {
        id: 1234,
        nickname: "마장동 삼겹살",
        badge_image_url: "",
      },
      content: "삼겹살이 제일 맛있는 것 같아요!",
      agreed_number: 123,
      disagreed_number: 45,
      created_date: "2023-03-25 14:22:00",
    },
  },
  {
    vote: {
      id: 987,
      title: "이탈리안 중에 가장 맛있는 음식은?",
      image_url: "https://dummyimage.com/600x400/000/fff",
      content: "이탈리안 중에 가장 맛있는 음식은 무엇일까요?",
      is_event: false,
      is_anonymous: false,
      is_public: true,
      is_closed: false,
      is_deleted: false,
      start_date: "2023-04-02 09:00:00",
      end_date: "2023-04-15 17:00:00",
      hits: 5678,
      voted_number: 33,
      opinion_number: 7,
      tags: ["이탈리안", "맛집", "음식"],
    },
    writer: {
      id: 5678,
      nickname: "피자나라",
      badge_image_url: "https://dummyimage.com/100x100/000/fff",
    },
    vote_items: [
      {
        id: 12345,
        item_number: 1,
        title: "피자",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300",
        total_points: 654,
        voted_number: 45,
      },
      {
        id: 12346,
        item_number: 2,
        title: "파스타",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300",
        total_points: 432,
        voted_number: 36,
      },
      {
        id: 12347,
        item_number: 3,
        title: "린귄니",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300",
        total_points: 321,
        voted_number: 23,
      },
      {
        id: 12348,
        item_number: 4,
        title: "라자냐",
        iframe_link: "",
        image_url: "https://dummyimage.com/400x300",
        total_points: 789,
        voted_number: 54,
      },
    ],
    best_opinion: {
      id: 9876,
      writer: {
        id: 4321,
        nickname: "스파게티",
        badge_image_url: "https://dummyimage.com/100x100/000/fff",
      },
      content: "저는 스파게티가 가장 맛있다고 생각합니다!",
      agreed_number: 234,
      disagreed_number: 56,
      created_date: "2023-03-30 10:13:00",
    },
  },
];
