export const tmpReportList = {
  totalPage: 65,
  reportList: [
    {
      reportId: 1,
      reporterId: 12,
      reportedContentType: "opinion",
      reportedContentId: 15165,
      reportedReasonType: "spam",
      reportedReasonDetail: "광고입니다. 처리좀요.",
      isChecked: false,
    },
    {
      reportId: 2,
      reporterId: 57,
      reportedContentType: "opinion",
      reportedContentId: 2132,
      reportedReasonType: "spam",
      reportedReasonDetail: "This is clearly spam.",
      isChecked: true,
    },
    {
      reportId: 3,
      reporterId: 34,
      reportedContentType: "board",
      reportedContentId: 7856,
      reportedReasonType: "bad",
      reportedReasonDetail: "This content is inappropriate.",
      isChecked: false,
    },
    {
      reportId: 4,
      reporterId: 89,
      reportedContentType: "picket",
      reportedContentId: 6754,
      reportedReasonType: "spam",
      reportedReasonDetail: "Unwanted advertising.",
      isChecked: true,
    },
    {
      reportId: 5,
      reporterId: 21,
      reportedContentType: "opinion",
      reportedContentId: 4682,
      reportedReasonType: "bad",
      reportedReasonDetail: "Content is offensive.",
      isChecked: false,
    },
    {
      reportId: 6,
      reporterId: 74,
      reportedContentType: "board",
      reportedContentId: 5983,
      reportedReasonType: "spam",
      reportedReasonDetail: "This is clearly spam.",
      isChecked: false,
    },
    {
      reportId: 7,
      reporterId: 46,
      reportedContentType: "picket",
      reportedContentId: 3472,
      reportedReasonType: "bad",
      reportedReasonDetail: "Content is misleading.",
      isChecked: true,
    },
    {
      reportId: 8,
      reporterId: 68,
      reportedContentType: "opinion",
      reportedContentId: 7865,
      reportedReasonType: "spam",
      reportedReasonDetail: "Unwanted advertising.",
      isChecked: false,
    },
    {
      reportId: 9,
      reporterId: 37,
      reportedContentType: "board",
      reportedContentId: 2356,
      reportedReasonType: "bad",
      reportedReasonDetail: "This content is inappropriate.",
      isChecked: true,
    },
  ],
};
